import { Universal } from 'koishi';
import * as eventType from '../type';
import { Stock } from '../../decoder/messages/system/consume/Stock';
import { BankCallback } from '../../decoder/messages/system/consume/BankCallback';
import { Forum } from '../../decoder/messages/system/forum/Forum';
import { Store } from '../../decoder/messages/system/store/Store';
import { Tasks } from '../../decoder/messages/system/tasks/Tasks';
import { Moments } from '../../decoder/messages/user/moments/Moments';
import { UserMoments } from '../../decoder/messages/user/moments/UserMoments';
import { Leaderboard } from '../../decoder/messages/system/leaderboard/Leaderboard';
import { SellerCenter } from '../../decoder/messages/system/store/SellerCenter';
import { SelfInfo } from '../../decoder/messages/user/profile/SelfInfo';
import { GradeUserCallback } from '../../decoder/messages/user/grade/GradeUserCallback';
import { FullUserProfileByName } from '../../decoder/messages/user/profile/FullUserProfileByName';
import { MediaListItem } from '../../encoder/system/media/getMusicList';
import { FollowList } from '../../encoder/user/follow/followList';
import { PaymentCallback } from '../../encoder/user/payment';
import { ProfileData } from '../../encoder/user/profile/updateSelfInfo';
import { ChangelogData } from '../../utils/changelog';
import type { RoomState } from '../../decoder/messages/system/room/BulkDataPacket';
import type { MediaWhitelistEntry } from '../../decoder/messages/admin/manage/MediaWhitelist';
import type { RoomRestrictionLevel } from '../../encoder/admin/manage/roomRestriction';
import type { MuteListEntry } from '../../decoder/messages/admin/manage/RoomRestriction';

export interface InternalType
{
  joinRoom(moveData: eventType.move): Promise<void>;
  moveRoom(roomIdOrMoveData: string | eventType.move, roomPassword?: string): Promise<void>;
  requestUserList(): void;
  kick(kickData: eventType.kickData): void;
  cutOne(cutOne?: eventType.cutOne): void;
  cutAll(): void;
  seekMedia(operation: '<' | '>', time: string): Promise<number | null>;
  jumpMedia(time: string): Promise<number | null>;
  exchangeMedia(id1: string, id2: string): void;
  nextMedia(): Promise<boolean>;
  clearMedia(): void;
  setMaxUser(setMaxUser?: eventType.setMaxUser): void;
  getRoomMaxUsers(): Promise<number | null>;
  setRoomMaxUsers(count?: number | null): Promise<boolean>;
  getRoomMaxGuests(): Promise<number | null>;
  setRoomMaxGuests(count?: number | null): Promise<boolean>;
  getRoomMinImpression(): Promise<number | null>;
  setRoomMinImpression(score?: number | null): Promise<boolean>;
  whiteList(whiteList: eventType.whiteList): void;
  getMediaWhitelist(): Promise<MediaWhitelistEntry[] | null>;
  addMediaWhitelist(username: string, duration: string | number, intro: string): Promise<boolean>;
  removeMediaWhitelist(uid: string): Promise<boolean>;
  clearMediaWhitelist(): Promise<boolean>;
  setRoomSpeechLevel(level: RoomRestrictionLevel): Promise<boolean>;
  setRoomMusicLevel(level: RoomRestrictionLevel): Promise<boolean>;
  setRoomBothLevel(level: RoomRestrictionLevel): Promise<boolean>;
  getMuteList(): Promise<MuteListEntry[] | null>;
  muteUser(type: 'chat' | 'music' | 'all', username: string, duration: string | number, intro: string): Promise<boolean>;
  unmuteUser(uid: string): Promise<boolean>;
  clearMuteList(): Promise<boolean>;
  getBlacklist(): Promise<MediaWhitelistEntry[] | null>;
  addBlacklist(username: string, duration: string | number, intro: string): Promise<boolean>;
  removeBlacklist(uid: string): Promise<boolean>;
  clearBlacklist(): Promise<boolean>;
  broadcast(broadcast: eventType.broadcast): void;
  getBroadcastRemaining(): Promise<number>;
  recordBroadcastAck(): Promise<number>;
  sendRoomNotice(notice: string): void;
  makeMusic(musicOrigin: eventType.musicOrigin): void;
  requestMusic(musicOrigin: eventType.musicOrigin): void;
  stockBuy(numberData: number): void;
  stockSell(numberData: number): void;
  stockGet(): Promise<Stock | null>;
  bankGet(): Promise<BankCallback | null>;
  bankDeposit(amount: number): void;
  bankWithdraw(amount: number): void;
  payment(uid: string, money: number, message?: string): Promise<PaymentCallback | null>;
  sendLike(uid: string, message?: string): void;
  sendDislike(uid: string, message?: string): void;
  followUser(uid: string): void;
  unfollowUser(uid: string): void;
  gradeUser(uid: string, score: number): Promise<GradeUserCallback | null>;
  cancelGradeUser(uid: string): Promise<boolean>;
  getUserMomentsByUid(uid: string): Promise<UserMoments | null>;
  getUserByName(name: string): Promise<Universal.User | undefined>;
  getUserListFile(): Promise<any>;
  getRoomListFile(): Promise<any>;
  getRoomList(): Promise<any>;
  getRoomStateFile(): Promise<RoomState | null>;
  getRoomId(): string;
  subscribeRoom(roomId: string): void;
  unsubscribeRoom(roomId: string): void;
  getFollowList(uid: string): Promise<FollowList | null>;
  getSelfInfo(): Promise<SelfInfo | null>;
  updateSelfInfo(profileData: ProfileData): Promise<boolean>;
  getMusicList(): Promise<MediaListItem[] | null>;
  getForum(): Promise<Forum | null>;
  getTasks(): Promise<Tasks | null>;
  getMoments(): Promise<Moments | null>;
  getLeaderboard(): Promise<Leaderboard | null>;
  getStore(): Promise<Store | null>;
  getSellerCenter(): Promise<SellerCenter | null>;
  addToCart(itemId: string): Promise<boolean>;
  removeFromCart(itemId: string): Promise<boolean>;
  getPendingPaymentOrders(): Promise<string | null>;
  getPendingReceiptOrders(): Promise<string | null>;
  getPendingConfirmationOrders(): Promise<string | null>;
  getPendingReviewOrders(): Promise<string | null>;
  getCompletedOrders(): Promise<string | null>;
  getAfterSaleOrders(): Promise<string | null>;
  getFavorites(): Promise<string | null>;
  getFollowedStores(): Promise<string | null>;
  getBalance(): Promise<number | null>;
  summonDice(diceId: number): void;
  getUserProfileByName(username: string): Promise<FullUserProfileByName | null>;
  getFullUserProfileByName(username: string): Promise<FullUserProfileByName | null>;
  getChangelog(): Promise<ChangelogData | null>;
}
